name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies for server
      working-directory: _work/Chat-Application/Chat-Application/server # Set the correct path to the server folder
      run: npm ci
    
    - name: Build the server
      working-directory: _work/Chat-Application/Chat-Application/server  # Ensure you're in the server directory
      run: npm run build --if-present
    
    - name: Set up environment variables
      working-directory: _work/Chat-Application/Chat-Application/server  # Stay in the server directory
      run: |
        touch .env
        echo "${{ secrets.secret }}" > .env
