name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      run: |
        cd server
        ls
      
    
      # uses: actions/setup-node@v4
      
      
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server
        ls
        npm ci
      working-directory: ./server
    
    - name: Set up environment file
      run: |
        touch .env
        echo "${{secrets.SECRET}}" > .env
      working-directory: ./server
